# Generated by Django 3.0.5 on 2020-04-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20200425_0136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderUpdate',
            new_name='Orderabc',
        ),
    ]
