# Generated by Django 3.0.5 on 2020-06-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20200618_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreceived',
            name='order_id',
            field=models.IntegerField(default=''),
        ),
    ]
