# Generated by Django 3.0.5 on 2020-06-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20200619_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDelivered',
            fields=[
                ('delivered_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('name', models.CharField(max_length=90)),
                ('address', models.CharField(max_length=200)),
                ('items_details', models.TextField(max_length=5000)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
