# Generated by Django 3.0.5 on 2020-06-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_remove_orderdelivered_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDelivered',
        ),
    ]
